[project]
name = "narada"
version = "0.1.11.post1"
description = "Python client SDK for Narada"
license = "Apache-2.0"
readme = "README.md"
authors = [{ name = "Narada", email = "support@narada.ai" }]
requires-python = ">=3.11,<3.12"
dependencies = []

[project.urls]
Homepage = "https://github.com/NaradaAI/narada-python-sdk/narada"
Repository = "https://github.com/NaradaAI/narada-python-sdk"
Issues = "https://github.com/NaradaAI/narada-python-sdk/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/narada"]
