
[project]
name = "narada-pyodide"
version = "0.0.40"
description = "Pyodide-compatible Python client SDK for Narada"
license = "Apache-2.0"
readme = "README.md"
authors = [{ name = "Narada", email = "support@narada.ai" }]
requires-python = ">=3.12"
dependencies = [
    "narada-core==0.0.15",
    # Must be a supported version in https://pyodide.org/en/stable/usage/packages-in-pyodide.html
    "packaging==24.2",
]

[project.urls]
Homepage = "https://github.com/NaradaAI/narada-python-sdk/packages/narada-pyodide"
Repository = "https://github.com/NaradaAI/narada-python-sdk"
Issues = "https://github.com/NaradaAI/narada-python-sdk/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pyodide-py>=0.27.7"]

[tool.hatch.build.targets.wheel]
packages = ["src/narada"]

[tool.uv.sources]
narada-core = { workspace = true }
